databases:
  - name: ishimaru_DB  # 編集 (Renderで作成したデータベース名)
    databaseName: example_db_ishimaru_db  # 編集 (Renderで作成したデータベースのところにあるInfo>Connections>Database)
    user: example_db_ishimaru_user  # 編集 (Renderで作成したデータベースのところにあるInfo>Connections>Username)
    region: singapore

services:
  - type: web
    name: fruit_shop # 編集 (Renderで作成したWeb Serviceの名前)
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ishimaru_DB  # 編集 (Renderで作成したデータベース名)
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false